### ISSUE TITLE
Start webui.py problems

### ISSUE THREAD

**Issue by Andromeda108** [serpotapov/stable-diffusion-portable#13]
Здравствуйте, Сергей.

12 раз уже пытался запустить систему. Чистил, по новой запускал, перезагружался /tmp удалял...
В этом месте кода из webui.py

строка modules.sd_models.load_model() 
Вылетает по ошибке:       
loading stable diffusion model: OSError
Traceback (most recent call last):
  File "F:\sd\webui.py", line 111, in initialize
    modules.sd_models.load_model()
  File "F:\sd\modules\sd_models.py", line 406, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "F:\sd\repositories\stable-diffusion-stability-ai\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "F:\sd\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "F:\sd\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "F:\sd\repositories\stable-diffusion-stability-ai\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "F:\sd\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 99, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(version)
  File "F:\sd\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1801, in from_pretrained
    return cls._from_pretrained(
  File "F:\sd\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1849, in _from_pretrained
    with open(tokenizer_config_file, encoding="utf-8") as tokenizer_config_handle:
OSError: [Errno 22] Invalid argument: 'tmp/.cache\\huggingface\\hub\\models--openai--clip-vit-large-patch14\\snapshots\\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\\tokenizer_config.json'        

Чего то не так в tokenizer_config.json
tokenizer_config.json эта ссылка на файл содержащий
{
    "unk_token": {
        "content": "<|endoftext|>",
        "single_word": false,
        "lstrip": false,
        "rstrip": false,
        "normalized": true,
        "__type": "AddedToken"
    },
    "bos_token": {
        "content": "<|startoftext|>",
        "single_word": false,
        "lstrip": false,
        "rstrip": false,
        "normalized": true,
        "__type": "AddedToken"
    },
    "eos_token": {
        "content": "<|endoftext|>",
        "single_word": false,
        "lstrip": false,
        "rstrip": false,
        "normalized": true,
        "__type": "AddedToken"
    },
    "pad_token": "<|endoftext|>",
    "add_prefix_space": false,
    "errors": "replace",
    "do_lower_case": true,
    "name_or_path": "openai/clip-vit-base-patch32",
    "model_max_length": 77,
    "special_tokens_map_file": "./special_tokens_map.json",
    "tokenizer_class": "CLIPTokenizer"
}   
 И в нем ошибка Invalid argument, как я понял...

Работал на других сборках - все нормально.
Плюнул, скачал напрямую у Automatic - все работает. Ваша - никак не хочет...

Win10, gtx 1060-6g. Решил попробовать вашу - и никак...

Один раз запустился после 12 попыток. И все работало, генерило картинки. Это вот очень странно.
Потом опять - не хочет. 

Прошу совет.  
Чего ему надо? Он в виртуал инвайронмент работает. Файерволов и дефендоров нет. До этого все грузил. Пути короткие F:\SD.

Не хочу отладчиком проходить... Пайчармы ставить, вспоминать, ковырять...

В файле вывод консоли запуск и падение. [1.txt](https://github.com/serpotapov/stable-diffusion-portable/files/10925816/1.txt)

**Comment by Jadawin83** [comment]
Такая же фигня. Вчера пробовал поставить на домашнем компе, сначала думал что то не так сделал. Всё удалил, попробовал поставить в другую папку на другом диске, ничего не поменялось. Сегодня попробовал поставить на рабочем компе. Всё то же самое.
From https://github.com/AUTOMATIC1111/stable-diffusion-webui
 * branch            master     -> FETCH_HEAD
Already up to date.
venv "venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI
Launching Web UI with arguments: --xformers --autolaunch
Calculating sha256 for D:\Downloads\StableDifusion\models\Stable-diffusion\f222.ckpt: 9e2c6ceff3f6d6f65c6fb0e10d8e69d772871813be647fd2ea5d06e00db33c1f
Loading weights [9e2c6ceff3] from D:\Downloads\StableDifusion\models\Stable-diffusion\f222.ckpt
Creating model from config: D:\Downloads\StableDifusion\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Failed to create model quickly; will retry using slow method.
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
loading stable diffusion model: OSError
Traceback (most recent call last):
  File "D:\Downloads\StableDifusion\webui.py", line 111, in initialize
    modules.sd_models.load_model()
  File "D:\Downloads\StableDifusion\modules\sd_models.py", line 406, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "D:\Downloads\StableDifusion\repositories\stable-diffusion-stability-ai\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\Downloads\StableDifusion\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "D:\Downloads\StableDifusion\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "D:\Downloads\StableDifusion\repositories\stable-diffusion-stability-ai\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\Downloads\StableDifusion\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 99, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(version)
  File "D:\Downloads\StableDifusion\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1801, in from_pretrained
    return cls._from_pretrained(
  File "D:\Downloads\StableDifusion\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1849, in _from_pretrained
    with open(tokenizer_config_file, encoding="utf-8") as tokenizer_config_handle:
OSError: [Errno 22] Invalid argument: 'tmp/.cache\\huggingface\\hub\\models--openai--clip-vit-large-patch14\\snapshots\\8d052a0f05efbaefbc9e8786ba291cfdf93e5bff\\tokenizer_config.json'


Stable diffusion model failed to load, exiting
Для продолжения нажмите любую клавишу . . .

**Comment by serpotapov** [comment]
Приветствую 🖐
Только что обновили сборку.
Перекачайте и запустите снова.
