### ISSUE TITLE
ERROR: Wheel 'torch' 

### ISSUE THREAD

**Issue by Unbezwingba** [serpotapov/stable-diffusion-portable#17]
Sorry for bothering

Same trouble while manually instaling automatic1111
P.s. There ppl also has the related trouble but it was not solved (somehow cmdr2 version is working)

Thanks alot

Collecting torch==1.13.1+cu117
  Downloading https://download.pytorch.org/whl/cu117/torch-1.13.1%2Bcu117-cp310-cp310-win_amd64.whl (2255.4 MB)
     ------------------------------ --------- 1.7/2.3 GB 2.3 MB/s eta 0:03:55
ERROR: Wheel 'torch' located at C:\stable-diffusion-portable-main\tmp\pip-unpack-pwlrcxn6\torch-1.13.1+cu117-cp310-cp310-win_amd64.whl is invalid.

[notice] A new release of pip available: 22.2.1 -> 23.0.1
[notice] To update, run: C:\stable-diffusion-portable-main\venv\Scripts\python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "C:\stable-diffusion-portable-main\launch.py", line 380, in <module>
    prepare_environment()
  File "C:\stable-diffusion-portable-main\launch.py", line 284, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "C:\stable-diffusion-portable-main\launch.py", line 97, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "C:\stable-diffusion-portable-main\venv\Scripts\python.exe" -m pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
Error code: 1

**Comment by Unbezwingba** [comment]
Mainly uninstalled python and all cache deleted through CCleaner as well as venv path in the directory.
Reboot all the process everything gone smooth.
Thanks)
