### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by Slavko56789** [serpotapov/stable-diffusion-portable#18]
[notice] A new release of pip available: 22.2.1 -> 23.0.1
[notice] To update, run: D:\SD2023\stable-diffusion-portable-main\venv\Scripts\python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "D:\SD2023\stable-diffusion-portable-main\launch.py", line 380, in <module>
    prepare_environment()
  File "D:\SD2023\stable-diffusion-portable-main\launch.py", line 287, in prepare_environment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "D:\SD2023\stable-diffusion-portable-main\launch.py", line 137, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "D:\SD2023\stable-diffusion-portable-main\launch.py", line 113, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "D:\SD2023\stable-diffusion-portable-main\venv\Scripts\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

**Comment by serpotapov** [comment]
Для запуска Stable Diffusion нужна видеокарта от NVIDIA.
