### ISSUE TITLE
torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by AlexRiman** [serpotapov/stable-diffusion-portable#19]
Добрый день! Прошу помощи! При попытке запуска обучения выдает следующую ошибку:

```
To create a public link, set `share=True` in `launch()`.
Startup time: 18.8s (import gradio: 4.9s, import ldm: 0.9s, other imports: 2.1s, load scripts: 0.8s, load SD checkpoint: 9.5s, create ui: 0.2s, gradio launch: 0.2s).
Training at rate of 2e-05 until step 800
Preparing dataset...
100%|██████████████████████████████████████████████████████████████████████████████████| 58/58 [00:26<00:00,  2.21it/s]
  0%|                                                                                        | 0/10000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\stable-diffusion-portable-main\modules\hypernetworks\hypernetwork.py", line 660, in train_hypernetwork
    scaler.scale(loss).backward()
  File "C:\stable-diffusion-portable-main\venv\lib\site-packages\torch\_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "C:\stable-diffusion-portable-main\venv\lib\site-packages\torch\autograd\_init_.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "C:\stable-diffusion-portable-main\venv\lib\site-packages\torch\autograd\function.py", line 267, in apply
    return user_fn(self, *args)
  File "C:\stable-diffusion-portable-main\venv\lib\site-packages\torch\utils\checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "C:\stable-diffusion-portable-main\venv\lib\site-packages\torch\autograd\_init_.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 4.00 GiB total capacity; 3.11 GiB already allocated; 0 bytes free; 3.16 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Calculating sha256 for C:\stable-diffusion-portable-main\models\hypernetworks\La01na.pt: 9b06e4f510d306c99a61a4985b8af19ffba4d1287004b827ea93288974e3b376
Applying xformers cross attention optimization.
```

У меня GTX 1650  4 гб

Пробовал решить проблему добавляя в bat файл комманды:
--medvram --opt-split-attention
--lowvram --always-batch-cond-uncond --opt-split-attention
--lowvram --opt-split-attention
С параметром lowvram вообще сообщает что обучение не возможно.

Так же пробовал добавить параметр:
set PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.6,max_split_size_mb:128
Но результата это не дало.
Подскажите в какую сторону копать? Буду очень признателен!

P.S. 
Sampling steps у меня 22
Max Steps 10000
Hypernetwork Learning rate: 2e-5:800, 8e-6:1600, 5e-6

Может ли быть проблема в самих фото, они у меня 512х512 формате PNG?

**Comment by Unbezwingba** [comment]
Here are some solutions that I found out
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Optimizations
Also:
Try generating 512x512
with these parameters
 --lowvram --xformers --always-batch-cond-uncond
