### ISSUE TITLE
AttributeError during installation

### ISSUE THREAD

**Issue by cleanmaharaj** [serpotapov/stable-diffusion-portable#20]
```
Traceback (most recent call last):
  File "H:\stable-diffusion-portable-main\launch.py", line 352, in <module>
    start()
  File "H:\stable-diffusion-portable-main\launch.py", line 347, in start
    webui.webui()
  File "H:\stable-diffusion-portable-main\webui.py", line 243, in webui
    shared.demo = modules.ui.create_ui()
  File "H:\stable-diffusion-portable-main\modules\ui.py", line 459, in create_ui
    with gr.Blocks(analytics_enabled=False) as txt2img_interface:
  File "H:\stable-diffusion-portable-main\venv\lib\site-packages\gradio\blocks.py", line 1097, in __exit__
    self.config = self.get_config_file()
  File "H:\stable-diffusion-portable-main\venv\lib\site-packages\gradio\blocks.py", line 1073, in get_config_file
    "props": utils.delete_none(block.get_config())
  File "H:\stable-diffusion-portable-main\venv\lib\site-packages\gradio\components.py", line 322, in get_config
    "type": self.type,
AttributeError: 'Textbox' object has no attribute 'type'. Did you mean: 'style'?
```

This happened twice during installation on different PC. Windows 10 and Windows 11.
After this error I can run server as usually, and everything seems to work fine. But I dont know, it can be affected on stable work?

**Comment by serpotapov** [comment]
Close this window and launch webui-user.bat.

**Comment by cleanmaharaj** [comment]
> Close this window and launch webui-user.bat.

Yeah, I understand. This error cant be affected  on server working?

**Comment by serpotapov** [comment]
No. All will be work fine.
