### ISSUE TITLE
RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same

### ISSUE THREAD

**Issue by adanis11** [serpotapov/stable-diffusion-portable#27]
Полный текст ошибки
Startup time: 35.9s (import torch: 1.8s, import gradio: 1.4s, import ldm: 0.6s, other imports: 1.4s, list SD models: 0.2s, load scripts: 1.3s, load SD checkpoint: 10.5s, create ui: 14.7s, gradio launch: 3.9s).
Error verifying pickled file from C:\Stable diffusion portable\stable-diffusion-portable-main\models\VAE-approx\model.pt:
Traceback (most recent call last):
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\safe.py", line 132, in load_with_extra
    check_pt(filename, extra_handler)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\safe.py", line 90, in check_pt
    unpickler.load()
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\safe.py", line 27, in persistent_load
    return TypedStorage(_internal=True)
TypeError: TypedStorage.__new__() got an unexpected keyword argument '_internal'

The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.

Error completing request
Arguments: ('task(8co1r4t7cc9qhzw)', 'cat', 'inscription, letter, glyph,((lettering)),((text)),((sign)),stacked torsos, totem pole, deformed, sad, bad anatomy, disfigured, poorly drawn face, mutation, mutated, extra limb, ugly, disgusting, poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed hands, blurry, mutated hands and fingers, watermark, watermarked, oversaturated, censored, distorted hands, amputation, missing hands, obese, doubled face, double hands, blur, blurred skin, asian, bw, sepia, emotionless mood, ungry, anime, penis, fake, drawing, illustration, boring, long neck, out of frame, extra fingers, mutated hands, monochrome, cgstation, flat chested, multiple subjects, extra heads, text, watermarks, logo, lowres, bad hands, error, missing fingers, extra digit, fewer digits, cropped, worst quality, jpeg artifacts, signature, username, large breasts,bad-hands-5', [], 20, 0, False, False, 1, 1, 8, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, False, 'positive', 'comma', 0, False, False, '', 'Illustration', 'svg', True, True, False, 0.5, True, 16, True, 16, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, 50) {}
Traceback (most recent call last):
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\processing.py", line 515, in process_images
    res = process_images_inner(p)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\processing.py", line 608, in process_images_inner
    sd_vae_approx.model()
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\sd_vae_approx.py", line 42, in model
    sd_vae_approx_model.load_state_dict(torch.load(model_path, map_location='cpu' if devices.device.type != 'cuda' else None))
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1624, in load_state_dict
    raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict)))
TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.

  0%|                                                                                           | 0/20 [00:06<?, ?it/s]
Error completing request
Arguments: ('task(9q265shiklngo6o)', 'cat', 'inscription, letter, glyph,((lettering)),((text)),((sign)),stacked torsos, totem pole, deformed, sad, bad anatomy, disfigured, poorly drawn face, mutation, mutated, extra limb, ugly, disgusting, poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed hands, blurry, mutated hands and fingers, watermark, watermarked, oversaturated, censored, distorted hands, amputation, missing hands, obese, doubled face, double hands, blur, blurred skin, asian, bw, sepia, emotionless mood, ungry, anime, penis, fake, drawing, illustration, boring, long neck, out of frame, extra fingers, mutated hands, monochrome, cgstation, flat chested, multiple subjects, extra heads, text, watermarks, logo, lowres, bad hands, error, missing fingers, extra digit, fewer digits, cropped, worst quality, jpeg artifacts, signature, username, large breasts,bad-hands-5', [], 20, 0, False, False, 1, 1, 8, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, False, 'positive', 'comma', 0, False, False, '', 'Illustration', 'svg', True, True, False, 0.5, True, 16, True, 16, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, 50) {}
Traceback (most recent call last):
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\processing.py", line 515, in process_images
    res = process_images_inner(p)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\processing.py", line 669, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\processing.py", line 887, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\sd_samplers_kdiffusion.py", line 377, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\sd_samplers_kdiffusion.py", line 251, in launch_sampling
    return func()
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\sd_samplers_kdiffusion.py", line 377, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\sd_samplers_kdiffusion.py", line 170, in forward
    sd_samplers_common.store_latent(torch.cat([x_out[i:i+1] for i in denoised_image_indexes]))
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\sd_samplers_common.py", line 58, in store_latent
    shared.state.assign_current_image(sample_to_image(decoded))
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\sd_samplers_common.py", line 46, in sample_to_image
    return single_sample_to_image(samples[index], approximation)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\sd_samplers_common.py", line 35, in single_sample_to_image
    x_sample = sd_vae_approx.model()(sample.to(devices.device, devices.dtype).unsqueeze(0))[0].detach()
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\modules\sd_vae_approx.py", line 28, in forward
    x = layer(x)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\extensions-builtin\Lora\lora.py", line 323, in lora_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lora(self, input)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Stable diffusion portable\stable-diffusion-portable-main\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same

Есть смысл переустанавливать? До этого все работало

**Comment by serpotapov** [comment]
Приветствую 🖐
В webui-user.bat в аргументах запуска допишите: `--disable-safe-unpickle`
Далее ошибки прошу обсуждать в Discord ➜ https://discord.gg/xpuct
