### ISSUE TITLE
How to fix?

### ISSUE THREAD

**Issue by takenava** [serpotapov/stable-diffusion-portable#5]
loading stable diffusion model: OutOfMemoryError
Traceback (most recent call last):
  File "C:\stable-diffusion-portable\webui.py", line 111, in initialize
    modules.sd_models.load_model()
  File "C:\stable-diffusion-portable\modules\sd_models.py", line 411, in load_model
    sd_model.to(shared.device)
  File "C:\stable-diffusion-portable\venv\lib\site-packages\pytorch_lightning\core\mixins\device_dtype_mixin.py", line 113, in to
    return super().to(*args, **kwargs)
  File "C:\stable-diffusion-portable\venv\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "C:\stable-diffusion-portable\venv\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\stable-diffusion-portable\venv\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\stable-diffusion-portable\venv\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "C:\stable-diffusion-portable\venv\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "C:\stable-diffusion-portable\venv\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 1.71 GiB already allocated; 0 bytes free; 1.75 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Stable diffusion model failed to load, exiting
Для продолжения нажмите любую клавишу . . .

**Comment by XpucT** [comment]
The error CUDA out of memory basically means that memory of CUDA is out.
