### ISSUE TITLE
Не запускается на видеокарте Radeon

### ISSUE THREAD

**Issue by Danmer777v01** [serpotapov/stable-diffusion-portable#6]
Traceback (most recent call last):
  File "D:\stable-diffusion-portable-main\launch.py", line 360, in <module>
    prepare_environment()
  File "D:\stable-diffusion-portable-main\launch.py", line 272, in prepare_environment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "D:\stable-diffusion-portable-main\launch.py", line 129, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "D:\stable-diffusion-portable-main\launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "D:\stable-diffusion-portable-main\venv\Scripts\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

**Comment by serpotapov** [comment]
Приветствую 🖐
Для AMD есть инструкция в репо AUTOMATIC1111.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs
