### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by 0-NiK-0** [serpotapov/stable-diffusion-portable#7]
При генерации изображения на вкладке txt2img доходит до 95%, далее выдаёт ошибку: 
`TypeError: 'NoneType' object is not subscriptable`

**Comment by serpotapov** [comment]
Нужен полный скриншот консоли.
Лучше на форум ➜ https://win10tweaker.ru/sd

**Comment by 0-NiK-0** [comment]
```
From https://github.com/AUTOMATIC1111/stable-diffusion-webui
 * branch            master     -> FETCH_HEAD
Already up to date.
venv "venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI
Launching Web UI with arguments: --xformers --autolaunch
Loading weights [9e2c6ceff3] from D:\stable-diffusion-portable-main\models\Stable-diffusion\f222.ckpt
Creating model from config: D:\stable-diffusion-portable-main\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 3.8s (load weights from disk: 1.3s, create model: 0.4s, apply weights to model: 0.4s, apply half(): 0.5s, move model to device: 0.5s, load textual inversion embeddings: 0.8s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.05it/s]
Error verifying pickled file from D:\stable-diffusion-portable-main\models\Codeformer\tmpf5u2so5j::02<00:00,  7.52it/s]
Traceback (most recent call last):
  File "D:\stable-diffusion-portable-main\modules\safe.py", line 81, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "D:\stable-diffusion-portable-main\python\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "D:\stable-diffusion-portable-main\python\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable-diffusion-portable-main\modules\safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "D:\stable-diffusion-portable-main\modules\safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


Error completing request
Arguments: ('task(7rjsn38qf0unub4)', 'Little girl holding a cat in her hand', 'deformed, bad anatomy, disfigured, poorly drawn face, mutation, mutated, extra limb, ugly, disgusting, poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed hands, blurry, ((((mutated hands and fingers)))), watermark, watermarked, oversaturated, censored, distorted hands, amputation, missing hands, obese, doubled face, double hands', [], 20, 0, True, False, 1, 1, 8, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "D:\stable-diffusion-portable-main\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-portable-main\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-portable-main\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "D:\stable-diffusion-portable-main\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "D:\stable-diffusion-portable-main\modules\processing.py", line 661, in process_images_inner
    x_sample = modules.face_restoration.restore_faces(x_sample)
  File "D:\stable-diffusion-portable-main\modules\face_restoration.py", line 19, in restore_faces
    return face_restorer.restore(np_image)
  File "D:\stable-diffusion-portable-main\modules\codeformer_model.py", line 88, in restore
    self.create_models()
  File "D:\stable-diffusion-portable-main\modules\codeformer_model.py", line 65, in create_models
    checkpoint = torch.load(ckpt_path)['params_ema']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by serpotapov** [comment]
Перекачайте модель f222.
А лучше скачать Deliberate.

**Comment by 0-NiK-0** [comment]
Ошибка возникает во всех моделях включая Deliberate скаченной по ссылке из описания.

**Comment by serpotapov** [comment]
Какое железо у Вас?

**Comment by 0-NiK-0** [comment]
У меня достаточно мощный ноутбук
Процессор: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
Видеокарта: NVIDIA GeForce RTX 3070 Laptop GPU
ОЗУ: 32 ГБ
ОС: Windows 11 Pro

**Comment by 0-NiK-0** [comment]
Portable Stable Diffusion и модель Deliberate я скачал 19.02.2023, сегодня установил.
Настройки все по умолчанию стоят.
Я сначала эту ошибку получил в Deliberate, потом попробовал поставить f222, ошибка повторилась.
В окне появляется картинка сгенерированная по моему запросу, до 95% она меняется, потом исчезает, выскакивает ошибка.

**Comment by serpotapov** [comment]
Уберите в командах для запуска ключ --xformers
И попробуйте снова запустить.

**Comment by 0-NiK-0** [comment]
Я стёр в webui-user.bat ключ –xformers, ничего не изменилось, ошибка осталась.

**Comment by 0-NiK-0** [comment]
Скорей всего моя проблема была вызвана сбоем во время установки. 
Я всё заново скачал и установил, после чего ошибка исчезла :)
